PREFIX: '&b[&cDiscordWebhookPlugin&b]&e'
PERMISSION:
  DCSEND: 'discordwebhookplugin.send'
  RELOAD: 'discordwebhookplugin.reload'
PERMISSION_MESSAGE: '<prefix> You dont have permissions to run this command.'
WebHookURL: '' #URL From You WebHook

JOIN:
  ENABLED: true #Here you can specify whether the join messages are displayed.
  MESSAGE: '<player> joined the server'
LEAVE:
  ENABLED: true #Here you can specify whether the leave messages are displayed.
  MESSAGE: '<player> left the server'

DEATH:
  ENABLED: false
  MESSAGE: '<player> is died.'

MESSAGES:
  RELOAD: '<prefix> Configs reloaded!'
  LINK: '<prefix> &8» &ediscord.gg/example' #This message will send when a Player type /discord or /dc.
  SENDING: '**<player>:** ' #Here then comes the message from the player.
  SUCCESS: '<prefix> Your text has been successfully sent to Discord.' #Send this Message when the /dcsend Command is SUCCESS.
  ERROR: '<prefix> Your text must have more than one word.' #Send this Message when the player type /dcsend with no Text.