name: DiscordWebhookPlugin
version: '1.1'
main: de.codeali.discordwebhookplugin.DiscordWebhookPlugin
description: This plugin connects to your discord server, you can use it to send messages from Minecraft or join/leave and start/stop messages.
commands:
  dcsend:
    aliases:
      - discordsend
  discordwebhookplugin:
    aliases:
      - dwp
  discord:
    aliases:
      - dc